[package]
name = "ronvoy"
version = "0.1.0"
authors = ["Bobby Powers <bobbypowers@gmail.com>"]
edition = "2018"

[dependencies]
rustls = "0.18"
tokio-rustls = "0.14"
futures-util = "0.3"
tokio = { version = "0.2", features = [ "net", "io-std", "io-util", "rt-threaded" ] }
structopt = "0.3"
webpki-roots = "0.20"
