[workspace]

members = [
    "ronvoy-core",
    "ronvoy-proxy",
    "ronvoy-server",
    "test/upstream-service",
]

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
debug = true
panic = "abort"
# strip = true
