#!/bin/bash
set -euxo pipefail


cargo build --release --target x86_64-unknown-linux-musl
RUST_BACKTRACE=1 ./target/x86_64-unknown-linux-musl/release/ronvoy --cert ./server.pem --key ./server-key.pem
